name: Publish to crates.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  run-checks:
    uses: ./.github/workflows/check.yml
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Create GitHub Release (draft)
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "${{ github.ref_name }}" --draft --repo "${{ github.repository }}"
  publish-package:
    needs: [run-checks, draft-release]
    environment: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.cargo_registry_token }}
      run: |
        cargo publish
